### ISSUE TITLE
Discuss: Smaller binary vs. integrated web view

### ISSUE THREAD

**Issue by sieren** [sieren/QSyncthingTray#138]
Hey everyone,

I'd like to initiate a little discussion regarding the filesize of QST.
As we are displaying the Syncthing Web UI without depending on an external browser, we need to package a full blown browser library which results in a large binary (~100mb vs. what could be just around 10mb).

Is it worth including a browser or would you rather see a smaller binary and make QST spawn the default browser on the desktop? (This would potentially include entering your user credentials whenever the website gets loaded).

(Related: https://github.com/sieren/QSyncthingTray/issues/133 and more..)

**Comment by kirichkov** [comment]
I personally would prefer a smaller binary. 

As a third option - Isn't it possible to use the OS' integrated WebView instead of bundling a full-blown browser? I'm aware that this might not work at all under Linux with it's multitude of components that can run a GUI, but should be feasible under Windows and OS X. 
Forgive me if I'm talking rubbish, I have rather limited knowledge of programming for the Desktop.

**Comment by sieren** [comment]
Cool, I'll wait for some more input before making a final decision.

The third option is unfortunately not feasibly from a technical standpoint.
I suppose it is for Safari and Internet Explorer, though - at least for Windows - someone else with more expertise on IE would have to take over this job, as I find Windows APIs generally a pain in the ass to deal with.

**Comment by stevenbagley** [comment]
I agree that QST is large, but the size doesn't cause me any difficulties in downloading or running. I do like that in the current scheme it runs as a separate application, so that I can have a keybinding to raise just that window.

**Comment by Zillode** [comment]
I agree with @stevenbagley

**Comment by dionorgua** [comment]
Could we have at least compiler-time option to disable QtWebEngine usage?

I don't care about binary size, but qtwebengine is a nightmare for linux distros and probably will not be packaged in near future.

Or could we try to use QtWebKit for this? I know that it's outdated, feature limited, But if QtWebKit is enough to run web interface, it'll reduce binary size. 

PS. If compile-time option to disable QtWebEngine is ok, I can try to contribute a patch.

**Comment by sieren** [comment]
Oh, I had no idea QtWebEngine support on Linux is lacking. I was using QtWebKit before but removed it in https://github.com/sieren/QSyncthingTray/commit/90a91a1575814cbc5a8f1b7ec4475ff66c039275 since it was marked deprecated and general advice was not to use it anymore (I ran into some issues with some other feature which made me ultimately turn the switch).

How far spread is QtWebKit? Is it worth considering a compile-time switch to switch to QtWebKit?
I could look into that soon and try to abstract all the web stuff away to separate classes for easier modularity.

**Comment by sieren** [comment]
@dionorgua I moved this discussion into a separate issue. I assume you're using Linux? Might you be available for some initial testing?

**Comment by dionorgua** [comment]
Sure. The main reason why there is no QtWebEngine in Debian is because QtWebEngine is too complex with embedded copies of a lot of system libraries (for example zlib, ffmpeg, etc). Debian policy forbids this.

In any case QtWebKit for me sounds good. I'll subscribe to issue you mentioned and will test once you have something.

Also please let me know if you need some help with this.

**Comment by sieren** [comment]
Cool, thanks! I'd ping you once I got something, maybe you'd be up for conducting a code review on my PR and chime in with ideas and suggestions, something this project has been lacking so far.
