### ISSUE TITLE
Add Compile Time Flag for QWebEngine/QtWebKit

### ISSUE THREAD

**Issue by sieren** [sieren/QSyncthingTray#145]
As discussed in https://github.com/sieren/QSyncthingTray/issues/138 a compile-time flag to change Web-Engines (QWebEngine/QtWebKit) might be nice since apparently QWebEngine is lacking proper Linux packaging.

**Comment by dionorgua** [comment]
Thanks for considering this!

**Comment by sieren** [comment]
ping @dionorgua .. was travelling quite a bit today and took the time to take care of this :) There's a PR now. No support in with the QtCreator .pro file yet, but Cmake should work. Can you give this a shot and maybe check the PR?

**Comment by dionorgua** [comment]
Sure. I'll check it soon. Thanks a lot for your time.

**Comment by dionorgua** [comment]
It still requires a few changes to compile it here. Or can create pull request if you need:

1. I don't want to lie about QTDIR since it's Qt from distro. All files are in system dirs (headers in /usr/include, libs in /usr/lib, etc). Just commented out whole QTDIR logic for now. But I'm pretty sure that any random dir will work. Could we make it optional (at least on Linux). Please let me know if you need help with it.

2. find_package(Qt5Declarative) is not needed at all. I've compiled QSyncThing without QtDeclarative installed

3. qt5_use_modules(QSyncthingTray Widgets Network WebEngineWidgets WebKitWidgets) still references WebEngineWidgets even with QST_BUILD_WEBKIT defined.

4. I've added #include <memory> in two files to fix compilation errors. Probably you use precompiled headers.

5. Very minor. There is no need to ifdef  "/DBUILD_WEBKIT=1" vs "-DBUILD_WEBKIT=1" depending on platform. CMake is smart enough to handle it itself. Just try /D on Linux/Mac or -D on Windows. It should work.

Whole diff that allows me to compile it (I'm not asking to apply/pull it):
https://gist.github.com/dionorgua/ab7fd2e781e4fc1b153054e650405104#file-gistfile1-txt

Please let me know if you need any help with this. Just merge whatever you think is ok and I can create pull request for rest.

**Comment by sieren** [comment]
Hey, I've pushed a bunch of fixups and cleanups. Mind checking again? I think I ticked off all of your suggestions ;)

**Comment by dionorgua** [comment]
It works for me without any changes. Thanks a lot!.
I'll try to prepare debian package soon.

**Comment by sieren** [comment]
Thanks for your help! Closing this now as its merged to maste :)
