### ISSUE TITLE
Please clarify license

### ISSUE THREAD

**Issue by dionorgua** [sieren/QSyncthingTray#148]
Hi,

I've found that there is LICENSE.txt in the source root that appears to be LGPL2.1. At the same time all source files seems to be licensed as "LGPL3 or any later". Which one is correct? If it's LGPL3+, could you please update LICENSE.txt file to match actual license of package?

Also could you please also specify license for for media used:
- screenshots in media/ dir
- icons in resources

As far as I understand, color icons are just from official syncthing distro (and licensed under Mozilla Public License). Please confirm this if it's true. And what about black icons and gif files?

Another issue is that there are binary files (syncthing-inotify for mac, and icns files). Could you consider moving them away from repo? (generate icns during build using makeIcon.sh). I can try to help with this if needed.
If no, it's not big problem, I'll just strip them from debian source package.

Thanks a lot!.

**Comment by sieren** [comment]
I recall I've chosen LGPL back then due to Qt, but apparently this project can be any license since we're dynamically linked against Qt. If you have some advice on this, I'd appreciate it (e.g. I wouldn't be opposed to use MIT or BSD).

The color icons are indeed from Syncthing and I suppose under MPL, I noticed they are being used for `syncthing-gtk` which is under GPL - (ping @calmh - maybe you can chime in here).
Not sure if this poses a problem.

As for the last part, `syncthing-inotify` shouldn't even be in this repo anymore as it's not being used.   
As for the icns files, is it really necessary to generate them at build time? (and if so, why? Licensing issues?).
If you wanna file a PR on this I'd be happy to include it into the repo, I don't have that much time this week.

**Comment by dionorgua** [comment]
Hi,

Actually I don't care about license at all. Just need to figure one which one is actually used. As far as I understand it's LGPL3+ right now with wrong LICENSE.txt file. It's ok for me. Please just update LICENSE file.

And what about b/w icons and gif files?

As about icns. I'll file PR on this soon!.

**Comment by calmh** [comment]
The icons are MPLv2, yes.

**Comment by calmh** [comment]
I expect that's entirely valid as long as you make available the source, such as it is, for those images. The source might be == the image for all I know. But then they are under MPLv2 at least. I don't think this is a problem in any way or form. I certainly won't make it one.

**Comment by sieren** [comment]
@dionorgua beware that generating the icns file should need to happen cross-platform in case you want to remove it entirely (at least as far as I remember). I'm currently generating OSX/Windows releases with `qmake` and the respective `deploy` utilities which I eventually wanna move away from and rely on cmake alone for this. 

Thanks for the info @calmh 👍

**Comment by dionorgua** [comment]
Ah. I was not aware that you also use qmake. In any case I think it's ok to keep icns files in git repo.

**Comment by dionorgua** [comment]
Am I right that b/w and gif files were created by you based on syncting icons?

In such case they are MPLv2

**Comment by sieren** [comment]
@dionorgua that is correct.

**Comment by dionorgua** [comment]
Thanks a lot!. Now it's clear.
