### ISSUE TITLE
Fix Resume after Standby Bug

### ISSUE THREAD

**Issue by sieren** [sieren/QSyncthingTray#176]
After a longer period of standby, QST shows "Not Connected" occasionally.

**Comment by meztup** [comment]
Yes. This happens on Windows 7 x64, sometimes after only a couple of hours of standby time. Other projects that use Qt seem to be having the same issues, claiming it to be a problem with Qt that might be fixable with a patch.

If I resume from standby and notice that the QST icon is grey, then I know the issue is actively occurring and that I need to restart QST to resolve. This is the **only** time that I see the grey icon -- possibly indicating that QST might have enough knowledge of the issue to auto-restart itself if Qt can't be fixed.

Meanwhile, Syncthing and iNotify both function as expected--QST just can't talk to the API.

**Comment by sieren** [comment]
I've started rewriting the whole process handling mechanism a few days ago, might take a while but will hopefully fix these issues.

**Comment by sieren** [comment]
I think I finally tracked down the bug. Deployed a fix (https://github.com/sieren/QSyncthingTray/pull/184)  but will do a new release once im certain this solves it.
