### ISSUE TITLE
Move QTDIR to cmake variable?

### ISSUE THREAD

**Issue by marco-m** [sieren/QSyncthingTray#190]
Hello,

I do a lot of cmake development and I was surprised by the way QSyncthingTray
uses to specify where to find Qt: with an environment variable.

I have to do something like

```
QTDIR=/path/to/qt cmake ...
```

as opposed to the standard cmake-way:

```
cmake -D CMAKE_PREFIX_PATH=/path/to/qt ...
```

I'll be happy to provide a patch but I wanted to check before :-)

What I propose is:

- get rid of `QTDIR` env variable and switch to `CMAKE_PREFIX_PATH`, or even convert QTDIR from env variable to cmake variable (`cmake -D QTDIR=/path/to/qt`).
- Adapt travis configuration accordingly
- Adapt appveyour conf if needed (didn't check yet)

What do you think?

**Comment by sieren** [comment]
I think going the standard CMAKE way makes sense, yeah. Not entirely sure why I did this, presumable because I worked with `gyp` before and I worked on a Qt project which was using this approach.

I'd be happy to merge a fix (so far I've been more or less the only maintainer of this and I've got a few other tasks on my radar for the next QST version).

If you decide to provide one, make sure to update the README as well :)
